Question 1
Create a shape (3, 4) Numpy array named arr as follow table, and format dtype as float32
1.2	1.4	1.6	1.8
2.3	2.5	2.7	2.9
3.4	3.6	3.8	4.0

array([[1.2, 1.4, 1.6, 1.8],
       [2.3, 2.5, 2.7, 2.9],
       [3.4, 3.6, 3.8, 4. ]], dtype=float32)


In [10]:
import numpy as np
arr= np.linspace(1.2,4,15, endpoint = True) 
arr=arr.astype('float32').reshape(3,5)

Question 2
Write code to show:
(a)	arr’s shape, and
(b)	dtype


In [11]:
print(arr.shape)

print(arr.dtype)

(3, 5)
float32


Question 3
Write code to calculate the square root of the arr, store the value in arr_sqrt and show the value.


In [12]:
import math
arr1=[1.2, 1.4, 1.6, 1.8]
arr2=[2.3, 2.5, 2.7, 2.9]
arr3=[3.4, 3.6, 3.8, 4. ]

sq_arr1=(math.sqrt(i) for i in arr1)
sq_arr2=(math.sqrt(i) for i in arr2)
sq_arr3=(math.sqrt(i ) for i in arr3)
arr_sqrt=np.vstack((arr1,arr2,arr3))
print(arr_sqrt)

[[1.2 1.4 1.6 1.8]
 [2.3 2.5 2.7 2.9]
 [3.4 3.6 3.8 4. ]]


In [ ]:
Question 4
Create a new Boolean array named arr2, to store the Boolean value of checking arr each value is greater and equal to 2.7. 
 >>> arr2
array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])
