# NumPy Exercises

## 1. Import numpy as np and print the version number.

In [4]:
import numpy as np
print(np.__version__)


2.0.2


## 2. Create a 1D array of numbers from 0 to 9 
$> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr= np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


## 3. Create a 3×3 numpy boolean array of all True’s 
<pre>
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)  </pre>

In [68]:
np.ones((3,3), dtype=bool)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. Extract items that satisfy a given condition from 1D array
<pre>
Extract all odd numbers from arr

Given that:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:
array([1, 3, 5, 7, 9]) </pre>

In [24]:
arr= np.array(range(10))
arr[arr%2!= 0]


array([1, 3, 5, 7, 9])

## 5. Replace items that satisfy a condition with another value in numpy array
<pre>
Replace all odd numbers in arr with -1

Given Input (in #4):
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]) </pre>

In [94]:
arr=np.array(range(10))
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##  6. Replace items that satisfy a condition without affecting the original array, and use np.where() function, and store value in arr2
<pre>
Replace all odd numbers in arr with -1 without changing arr

Given Input:
arr = np.arange(10)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
arr2
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
</pre>

In [38]:
arr=np.array(range(10))
np.where(arr%2 !=0, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 7. Reshape an array
Convert a 1D array to a 2D array with 2 rows
<pre>
Given Input:
np.arange(10)
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])</pre>

In [47]:
arr2=np.arange(10).reshape((2,5))
print(arr2)


[[0 1 2 3 4]
 [5 6 7 8 9]]


## 8. Stack two arrays vertically
<pre>
Stack arrays a and b vertically

Given Input:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Desired Output:
array([[0, 1, 2, 3, 4],
      [5, 6, 7, 8, 9],
      [1, 1, 1, 1, 1],
      [1, 1, 1, 1, 1]])</pre>

In [51]:
a=np.arange(10).reshape(2, -1)
b= np.repeat(1,10).reshape(2,-1)

np.concatenate((a, b), axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. Stack two arrays horizontally
<pre>Stack the arrays a and b horizontally.

Given Input:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Desired Output:
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
      [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]) </pre>

In [52]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10. Generate custom sequences in numpy without hardcoding
<pre>Create the following pattern without hardcoding. 
Use only numpy functions and the below input array arr

Given Input:
arr = np.array([1,2,3])

Desired Output:
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])</pre>

In [69]:
arr = np.array([1,2,3])
np.concatenate([np.repeat(arr,3), np.tile(arr,3)],axis = 0)


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. Get the common items between two python numpy arrays
<pre>
Get the common items between a and b

Given Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:
array([2, 4])</pre>

In [71]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

## 12. Remove from one array those items that exist in another
<pre>From array a remove all items present in array b

Given Input:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

Desired Output:
array([1,2,3,4])

In [72]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

## 13. Get the positions where elements of two arrays match
<pre>Get the positions where elements of a and b match

Given Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:
(array([1, 3, 5, 7]),)</pre>

In [73]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

## 14. Extract all numbers between a given range from a numpy array
<pre>Get all items between 5 and 10 from a.

Given Input:
a = np.array([2, 6, 1, 9, 10, 3, 27])

Desired Output:
array([6, 9, 10]) 
or
[6, 9, 10]
</pre>

In [80]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

## 15. Make a python function that handles scalars to work on numpy arrays
<pre>Convert the function maxx that works on two scalars, to work on two arrays.

Given Input:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
$> 5

Desired Output:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
$> array([6, 7, 9, 8, 9, 7, 5])
or
[6, 7, 9, 8, 9, 7, 5]
</pre>

In [95]:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pairing= np.vectorize(maxx)
pairing(a,b)

array([6, 7, 9, 8, 9, 7, 5])

## 16. Swap two columns in a 2d numpy array
<pre>Swap columns 0 and 1 in the array arr.

Given Input:
arr = np.arange(9).reshape(3,3)
arr
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Desired Output:       
array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])       
       </pre>

In [88]:
arr = np.arange(9).reshape(3,3)
arr [:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## 17. Swap two rows in a 2d numpy array
<pre>Swap rows 0 and 2 in the array arr:

Given input:
arr = np.arange(9).reshape(3,3)
arr
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
       
Desired Output:
array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])
</pre>

In [89]:
arr = np.arange(9).reshape(3,3)
arr[[2,1,0],:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

## 18. Reverse the rows of a 2D array
<pre>Reverse the rows of a 2D array arr.
Given Input:
arr = np.arange(12).reshape(4,3)
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Desired Output:
array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])    
</pre>

In [90]:
arr = np.arange(12).reshape(4,3)
arr[[3,2,1,0],:]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

## 19. Reverse the columns of a 2D array
<pre>Reverse the columns of a 2D array arr.
Given Input:
arr = np.arange(15).reshape(3,5)
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Desired Output:
array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])
</pre>

In [92]:
arr = np.arange(15).reshape(3,5)
arr[:,[4,3,2,1,0]]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])