# This program is to practice 1+1 =2. really nice

## I am very handsome la
### This is a program for frankie

This is a plan

In [24]:
1+1

2

This cell is to print 3 hellos

In [25]:
for i in range(3):
    print('hello')

hello
hello
hello


In [26]:
x =3

In [27]:
print(x)

3


In [28]:
x**2

9

In [29]:
x

3

In [30]:
x
x+1

4

In [31]:
print(x)
print(x+1)

3
4


# Print Even numbers!

In [32]:
# This cell is to print all even number
for i in range(1, 21):
    if i % 2 == 0:
        print(i)

2
4
6
8
10
12
14
16
18
20


In [1]:
import numpy as np

print(np.__version__)

2.0.2


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print('Type of arr is', type(arr))

[1 2 3 4 5]
Type of arr is <class 'numpy.ndarray'>


In [4]:
type(arr)

numpy.ndarray

In [5]:
arr


array([1, 2, 3, 4, 5])

In [9]:
a = [1, 2, 3]
x = np.array(a)


In [13]:
x.ndim


1

In [14]:
a = [[1, 2, 3], [4, 5, 6]]
x = np.array(a)

In [15]:
x


array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x.ndim

2

In [18]:
np.array('a').ndim

0

In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [23]:
arr.ndim

3

In [24]:
x = np.array([[1, 2], [3, 4], [5,6], [7,8]])

In [25]:
print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
x.ndim

2

In [30]:
x = np.array(['a', 'b', 'c', 'd', 'e'])
str(x[-1])

'e'

In [32]:
x = np.array([[0, 1, 2, 3,],
              [10, 11, 12, 13,],
              [20, 21, 22, 23, ]])

In [43]:
x[::-1, 1:-1]

array([[21, 22],
       [11, 12],
       [ 1,  2]])

In [51]:
x = [1, 2, 3, 4, 5]
print(x[1:4:-1])
print(x[4:1:-1])
print(x[1::-1])
print(x[4::-1])

[]
[5, 4, 3]
[2, 1]
[5, 4, 3, 2, 1]


In [52]:
x = [[0, 1, 2, 3, 4,5 ],
     [10, 11, 12, 13, 14,15 ],
     [20, 21, 22, 23, 24,25 ],
     [30, 31, 32, 33, 34,35 ],
     [40, 41, 42, 43, 44,45 ],
     ]

In [53]:
a = np.array(x)

In [55]:
a[1:4,1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [60]:
a[0:4, 3:][::-1, ::-1]

array([[35, 34, 33],
       [25, 24, 23],
       [15, 14, 13],
       [ 5,  4,  3]])

In [63]:
a[3::-1,:2:-1]

array([[35, 34, 33],
       [25, 24, 23],
       [15, 14, 13],
       [ 5,  4,  3]])

In [67]:
x = np.array([[[1, 2],[3, 4]], [[5, 6],[7, 8]]])

In [69]:
x.ndim

3

In [70]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [74]:
y = np.array([
              [[1, 2],
               [3, 4]],

              [[5, 6],
               [7, 8]],

              [[5, 6],
               [7, 8]]
                        ])
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[5 6]
  [7 8]]]


In [78]:
y[0,0,0]

np.int64(1)

In [79]:
y[1, 1, 1]

np.int64(8)

In [80]:
y[2, 1, 0]

np.int64(7)

In [82]:
y.shape

(3, 2, 2)

In [84]:
slides, xdim, ydim = y.shape
print('The shape is ', slides, 'x ', xdim , 'x ', ydim )

The shape is  3 x  2 x  2


In [85]:
a, b = (1, 2)

In [86]:
print(a, b)

1 2


In [87]:
y.shape

(3, 2, 2)

In [88]:
a, b, c = y.shape

In [89]:
print(a, b, c)

3 2 2


In [99]:
print(f'{2**64:,}')

18,446,744,073,709,551,616


In [100]:
x = np.array([1, 2, 3, 4])

In [101]:
x.dtype

dtype('int64')

In [104]:
x = np.array([1, 2, 3, 4], dtype=np.int32)

In [107]:
x.dtype

dtype('int32')

In [109]:
x = np.array(['1', '2', '3', '4'])

In [110]:
x.dtype

dtype('<U1')

In [112]:
x = np.array([1, 2, 3, 4], dtype=np.str_)

In [113]:
x

array(['1', '2', '3', '4'], dtype='<U1')

In [114]:
y = np.array(['1', '2', '3'], dtype=np.int64)

In [115]:
y.dtype

dtype('int64')

In [116]:
z = np.array(['a', 'b', 'c'], dtype=np.int32)

ValueError: invalid literal for int() with base 10: 'a'

In [117]:
x = np.array([1, 2, 3, 4], dtype='U')

In [118]:
x

array(['1', '2', '3', '4'], dtype='<U1')

In [119]:
y = np.array([1, 2, 3, 4], dtype = 'i8')

In [120]:
y.dtype

dtype('int64')

In [123]:
y = np.array([1, 2, 3, 4], dtype='i4')
print(y.dtype)

int32


In [126]:
x = np.array ([10, 20, 30], dtype= 'U')

In [128]:
np.array(range(9))


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [129]:
np.array((3, 4, 5))

array([3, 4, 5])

In [131]:
x = np.array({1:2, 3:4})
print(x)

{1: 2, 3: 4}


In [136]:
x = np.array(list({1, 2, 3}))

In [137]:
x

array([1, 2, 3])

In [135]:
x

array({1, 2, 3}, dtype=object)

In [138]:
x = np.array(list({1:2, 3:4}))
x

array([1, 3])

In [140]:
x = np.array([1, 2, 3], dtype='f')
print(x)

[1. 2. 3.]


In [141]:
[1, 2, 3]

[1, 2, 3]

In [142]:
y = np.array([1.1, 2.2, 3.3], dtype = 'i8')
print(y.dtype)
print(y)

int64
[1 2 3]


In [143]:
y

array([1, 2, 3])

In [144]:
z = y.astype('f')
z

array([1., 2., 3.], dtype=float32)

In [146]:
z.shape

(3,)

In [149]:
x = np.array((1, 2, 3, 4, 5,) ,dtype = np.int32)

In [151]:
print(x.ndim)
print(x.shape)
y = x.astype('f')
print(y)
print(y.dtype)

1
(5,)
[1. 2. 3. 4. 5.]
float32


In [8]:
def sum(x, y):
    return x+y

In [13]:
x = [3, 4]
print(sum(x[0], x[1]))
print(*x)

7
3 4


In [14]:
y = (5, 6)
print(sum(*y))

11


In [19]:
def sum(x, y):
    return x+y
print(sum(*[4, 5])) # *[4, 5] -> 4, 5

param_dict = {'x': 10, 'y':20}
print(sum(**param_dict))
# **{'x': 10, 'y':20} --> x= 10, y=20

9
30


In [21]:
def multiply(a, b, c):
    return a * b * c

x = (10, 20, 30)
y = {'a': 3, 'b':4, 'c':5}

print(multiply(*x))
print(multiply(**y))

6000
60


In [26]:
def sum(a, b):
    return a+b

print(sum(3,4))
y = (5, 6)
print(sum(y[0], y[1]))
# y = (5, 6) --> *y --> 5, 6
# sum(*y) --> sum(5, 6) --> 11

p = {'a': 10, 'b': 20}
# p = {'a': 10, 'b': 20} --> **p --> a=10, b=20
# sum(**p) --> sum(a=10, b=20) --> 30
sum(**p)

7
11


30

In [36]:
import math
def sumx(*args):
    return math.fsum(args)
print(sumx(3, 4, 5, 6))
print(sumx(*[3, 4, 5, 6])) # --> 3, 4, 5, 6

18.0
18.0


In [43]:
import numpy as np
a = np.array([[1,4],[3,1]])
# print(np.sort(a)  )             # sort along the last axis
# np.sort(a, axis=None)     # sort the flattened array
np.sort(a, axis=0)        # sort along the first axis

array([[1, 1],
       [3, 4]])

In [44]:
a = np.array([[3, 9, 8],
              [5, 2, 5],
              [4, 7, 3]])
np.sort(a, axis=0)

array([[3, 2, 3],
       [4, 7, 5],
       [5, 9, 8]])

In [49]:
x = np.array([1, 2, 3, 4, 5])
x==3

array([False, False,  True, False, False])

In [50]:
all(x==3)

False

In [51]:
any(x==3)

True

In [60]:
y = np.array([2, 4, 6, 8 , 10])
z = (y % 2==1)
print(z)
print(any(z))
print(~z)
print( all(~z))

[False False False False False]
False
[ True  True  True  True  True]
True


In [65]:
x = np.array((1, 2, 3))
x[[True, False, True]]
x[np.array([True, False, True])]
arr =np.array( [False, True, False])
x[arr]

array([2])

In [68]:
x = np.array([1, 2, 3, 4, 5, 6])
arr = np.array([True, False, True, False, True, False])
print(x[arr])

[1 3 5]


In [71]:
arr2 =( x % 2 == 1)
print(arr2)
print(x[arr2])
print(x[x%2==1])

[ True False  True False  True False]
[1 3 5]
[1 3 5]


In [77]:
x = np.arange(1, 100)
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [79]:
x[x % 3 != 0]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29, 31, 32, 34, 35, 37, 38, 40, 41, 43, 44, 46, 47, 49, 50,
       52, 53, 55, 56, 58, 59, 61, 62, 64, 65, 67, 68, 70, 71, 73, 74, 76,
       77, 79, 80, 82, 83, 85, 86, 88, 89, 91, 92, 94, 95, 97, 98])

In [93]:
~np.array([True, False , True])

array([False,  True, False])

In [98]:
x = np.arange(1, 99)
x[(x % 3 == 0) &( x % 5 == 0)]

array([15, 30, 45, 60, 75, 90])

In [99]:
x[(x % 3 == 0) | ( x % 5 == 0)]

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36,
       39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72,
       75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96])

In [100]:
x[~ (x % 3 == 0)]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26, 28, 29, 31, 32, 34, 35, 37, 38, 40, 41, 43, 44, 46, 47, 49, 50,
       52, 53, 55, 56, 58, 59, 61, 62, 64, 65, 67, 68, 70, 71, 73, 74, 76,
       77, 79, 80, 82, 83, 85, 86, 88, 89, 91, 92, 94, 95, 97, 98])

In [126]:
x = np.arange(1, 100)
print(x)
print(x[(x >30) & (x < 60)])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
 55 56 57 58 59]


In [127]:
30 < 45 < 60

True

In [128]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [130]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)
print(arr1+arr2)

[30 32 34 36 38 40]
[30 32 34 36 38 40]


In [132]:
[1, 1, 1] + [2, 2, 2]
np.add([1, 1, 1], [2, 2, 2])

array([3, 3, 3])

In [134]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)
print(arr1 ** arr2)

[         1000       3200000     729000000 6553600000000          2500
             0]
[         1000       3200000     729000000 6553600000000          2500
             0]


In [136]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.abs(arr)

print(newarr)

[1 2 1 2 3 4]


In [137]:
population = [100, 200, 300, 250, 50 ]
np.cumsum(population)

array([100, 300, 600, 850, 900])

In [138]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
np.cumprod(x)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [139]:
x = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

In [142]:
np.sin(x)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [146]:
x = [1, 2, 3,2 ]
y = [4, 2, 3, 5]
np.intersect1d(x, y, assume_unique=False)

array([2, 3])

In [148]:
x = np.array('I am a boy'.split())
print(x)


['I' 'am' 'a' 'boy']


4

In [153]:
def stlen(st):
    return len(st)

stlen = np.frompyfunc(stlen, 1, 1)

x = np.array('I am a boy'.split())
stlen(x)


array([1, 2, 1, 3], dtype=object)

In [154]:
stlen('abc')

3

In [158]:
def pyth(x, y):
    return (x*x + y*y)**0.5

pyth = np.frompyfunc(pyth, 2, 1)
pyth([3, 5, 6], [4, 12, 8])

array([5.0, 13.0, 10.0], dtype=object)

In [171]:
def gt_3(x):
    return x > 3

gt_3 = np.frompyfunc(gt_3, 1, 1)
y = np.array([1, 2, 3, 2, 5, 6, 1])
print(gt_3(y))
print(y[x.astype(np.bool)])


[False False False False True True False]
[5 6]


In [174]:
def check_stlen(st):
    return len(st) > 3
check_stlen = np.frompyfunc(check_stlen, 1, 1)

words = input('Please enter your sentence: ').strip()
words_array = np.array(words.split())
print(words_array)
words_array[check_stlen(words_array).astype(np.bool)]

['mary' 'has' 'a' 'little' 'lamb']


array(['mary', 'little', 'lamb'], dtype='<U6')

In [176]:
check_stlen(['aasdfa', 'asdfaf'])

array([True, True], dtype=object)