In [1]:
1+1

2

## This program is to practise 1+1 =2

# from Lily

Nice

# Print Even Numbers!

In [2]:
#this cell is to print all even number
for i in range(1, 21):
    if i%2 == 0:
        print(i)

2
4
6
8
10
12
14
16
18
20


In [3]:
import numpy as np

print(np.version)

<module 'numpy.version' from 'c:\\Users\\User\\test_numpy\\.venv\\lib\\site-packages\\numpy\\version.py'>


In [6]:
arr = np.array([1,2,3,4,5])
print(arr)
print('Type of arr is ', type(arr))

[1 2 3 4 5]
Type of arr is  <class 'numpy.ndarray'>


In [11]:
x= np.array([1,2,3,4,5], ndmin =2)
print(x)

[[1 2 3 4 5]]


In [15]:
x= np.array([[1,2],[3,4],[5,6],[7,8]])
print(x)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [26]:
x= np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35]])
print(x)
print(x[1:4,1:4])
y=(x[::-1, ::-1])
print(y[0:4,0:3])

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[35 34 33]
 [25 24 23]
 [15 14 13]
 [ 5  4  3]]


In [32]:
x = np.array([1,2,3,4] , dtype ='i8')
x.dtype

dtype('int64')