# This program is to write a multiply function and use * to break the tuple

In [1]:
def multiply (a,b,c):
    return a*b*c

x= (10, 20, 30)
y= {'a':3,'b':4, 'c':5}

print(multiply(*x))
print(multiply(**y))

6000
60


# this program is to demonstrate sort function

#

In [4]:
import numpy as np

a= np.array([[1,4],[3,1]])
print(np.sort(a))    # sort along the last axis
print(np.sort(a, axis = None))  # sort the flattened array
print(np.sort(a, axis = 0)) # sort along the first axis

[[1 4]
 [1 3]]
[1 1 3 4]
[[1 1]
 [3 4]]


# this program is to demonstrate any and all

In [9]:
y= np.array([2,4,6,8,10])

print(all(y%2 == 0))

print(any(y%2 !=0))

print(all(~y))

True
False
True


# this program is to demonstrate how to select the value with True in an array (array filtering)

In [13]:
x= np.array((1,2,3))

x [[True, False, True]]
x[np.array([True, False, True])]
arr = np.array([False, True, False])
x[arr]

array([2])

In [15]:
x=np.array((1,2,3,4,5,6))
x[[True, False, True, False, True, False]]

array([1, 3, 5])

# To generate array with True false

In [18]:
arr2 = (x%2 ==1)
print(arr2)
print(x[arr2])

x[x%2 == 1]

[ True False  True False  True False]
[1 3 5]


array([1, 3, 5])

example: 1-99 divided by 3 list out and not divident by 3 list out

In [21]:
x=np.array(range(1,100)) # or use x = np.arrange(1, 100)
print(x)
arr3= (x%3 == 0)
print(x[arr3])
print(x[~arr3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[ 1  2  4  5  7  8 10 11 13 14 16 17 19 20 22 23 25 26 28 29 31 32 34 35
 37 38 40 41 43 44 46 47 49 50 52 53 55 56 58 59 61 62 64 65 67 68 70 71
 73 74 76 77 79 80 82 83 85 86 88 89 91 92 94 95 97 98]


# this is to demonstrate and '&' and or'|' and not '~'

In [24]:
~np.array([True, False, True]) & np.array([True, True, False])
~np.array([True, False, True]) | np.array([True, True, False])

array([ True,  True, False])

In [25]:
x [(x%3 == 0 )& (x % 5 ==0)]

array([15, 30, 45, 60, 75, 90])

In [35]:
import numpy as np

arr = np.array(range(1,100))

filter_arr = (arr > 30) & (arr <60)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False]
[31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
 55 56 57 58 59]


In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1, arr2)
newarr = np.sum ([arr1, arr2], axis = 1)
newarr = np.sum ([arr1, arr2], axis = 0)
print(newarr)

[1 2 3] [1 2 3]
[2 4 6]


In [41]:
x = [1,2,3,4,5,6,7,8,9,10]
np.cumprod(x)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

# this function is to make a function can operated as an array (with function name, input variable num, output variable num)

In [42]:
def pyth(x,y):
    return(x*x +y*y )**0.5

pyth = np.frompyfunc(pyth, 2, 1)

pyth([3,5,6], [4, 12, 8])

array([5.0, 13.0, 10.0], dtype=object)

In [45]:
def gt_3(x):
    return x >3

gt_3 = np.frompyfunction(gt_3, 1, 1)

print(gt_3(y))
print(y[x.astype(np.bool)])

AttributeError: module 'numpy' has no attribute 'frompyfunction'

In [3]:
import numpy as np


def check_stlen(st):
    return len(st) >3

check_stlen = np.frompyfunc(check_stlen, 1, 1)
words = input('Please enter your sentence').strip()
words_array = np.array(words.split())
print(words_array)
words_array[check_stlen(words_array).astype(np.bool)]

['mary' 'has' 'a' 'litttle' 'lamb']


array(['mary', 'litttle', 'lamb'], dtype='<U7')

In [4]:
check_stlen(['aasdfa', 'asdfaf'])

array([True, True], dtype=object)

In [31]:
import numpy as np
a, width = np.linspace(2,3,11, endpoint=True, retstep=True)
print(a, width)
y=np.astype(a*10, np.int32)
print(y)
filter_arr= (y%4!=0)
b=y[filter_arr]       
print(b)


[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3. ] 0.1
[20 21 22 23 24 25 26 27 28 29 30]
[21 22 23 25 26 27 29 30]


# this program is to creat a universal function to let user input a sentence and pick out all 'a's words, return True/False when user has inputted 'a'

In [58]:
def check_a (sentence):
    word = sentence.split(' ')
    ls=[]
    for i in word:
        if i.find('a')== True:
            ls.append(i)
    return ls

    
ycheck_a = np.frompyfunc(check_a, 1, 1)
y=(check_a('The rain in spain fall mainly on the plain'))


In [70]:
def checka(word):
    return 'a' in word.lower()
print(type(checka('Mary')))
checkb = np.frompyfunc(checka, 1, 1)
print(type(checkb('Mary')))

x = np.array('Mary has a little lamb'.split())
print(type(checkb(x)))
x[np.astype(checkb(x), np.bool)]


<class 'bool'>
<class 'bool'>
<class 'numpy.ndarray'>


array(['Mary', 'has', 'a', 'lamb'], dtype='<U6')

In [85]:
import numpy_financial as npf

principal = 3_700_000

periods = 30*12

interest_rate= 0.03625/12

npf.pmt(rate=interest_rate, nper=periods, pv =principal)



np.float64(-16873.898174820657)

In [86]:
investment = -10000
ireturn = [-10000, 1000, 1000, 1000, 1000, 11000]

npf.irr(ireturn)

0.10000000000000009

In [90]:
round(npf.npv(0.1,[-10000, 1000, 1000, 1000, 1000, 11000]))

0