Question 1
Create a shape (3, 4) Numpy array named arr as follow table, and format dtype as float32
1.2	1.4	1.6	1.8
2.3	2.5	2.7	2.9
3.4	3.6	3.8	4.0

array([[1.2, 1.4, 1.6, 1.8],
       [2.3, 2.5, 2.7, 2.9],
       [3.4, 3.6, 3.8, 4. ]], dtype=float32)


In [63]:
import numpy as np
arr=np.array([[1.2, 1.4, 1.6, 1.8],
       [2.3, 2.5, 2.7, 2.9],
       [3.4, 3.6, 3.8, 4. ]], dtype =np.float32)
print(arr)

[[1.2 1.4 1.6 1.8]
 [2.3 2.5 2.7 2.9]
 [3.4 3.6 3.8 4. ]]


Question 2
Write code to show:
(a)	arr’s shape, and
(b)	dtype


In [64]:
print(arr.shape)

print(arr.dtype)

(3, 4)
float32


Question 3
Write code to calculate the square root of the arr, store the value in arr_sqrt and show the value.


In [65]:
arr_sqrt=np.sqrt(arr)
print(arr_sqrt)

[[1.0954452 1.183216  1.264911  1.3416407]
 [1.5165751 1.5811388 1.6431677 1.7029387]
 [1.8439089 1.8973665 1.9493588 2.       ]]


Question 4
Create a new Boolean array named arr2, to store the Boolean value of checking arr each value is greater and equal to 2.7. 
 >>> arr2
array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [66]:
arr2=(arr>=2.7)
print([arr2])

[array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])]


Question 5
Multiply the arr by 3 then minus 2, store the value in arr_cal. And show the array value.


In [67]:
arr_cal = arr_sqrt*3-2
print(arr_cal)

[[1.2863355 1.5496478 1.794733  2.0249224]
 [2.5497255 2.7434168 2.9295034 3.1088161]
 [3.5317268 3.6920996 3.8480763 4.       ]]


Question 6
Write code to show:
(a)	arr max value, and
(b)	arr mean value, and
(c)	arr standard deviation


In [68]:
print(np.max(arr_cal))
print(np.mean(arr_cal))
print(np.std(arr_cal))

4.0
2.754917
0.8892499


Question 7
Access the shaded two value in arr, and output their multiplication value.  
1.2	1.4	1.6	1.8
2.3	2.5	2.7	2.9
3.4	3.6	3.8	4.0


In [69]:
arr[0,2]*arr[2,0]
print(arr[0,2]*arr[2,0])

5.44



Question 8
Write code to show the transpose of arr


In [70]:
arr.T

array([[1.2, 2.3, 3.4],
       [1.4, 2.5, 3.6],
       [1.6, 2.7, 3.8],
       [1.8, 2.9, 4. ]], dtype=float32)


Question 9
Write code to:
(a)	Reshape arr as (2,6) structure, and
(b)	Flatten arr and store the value in arr_flat


In [71]:
arr.reshape(2,6)
arr_flat= arr.flatten()
