In [2]:
import torch
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten= torch.arange(start=1, end=1000, step =77)
one_to_ten

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [3]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [4]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (e.g. float32 or float16)
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [5]:
float_32_tensor.dtype

torch.float32

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with pyTorch & deep learning
1. Tensors not right datatype 
2. Tensors not right shape
3. Tensors not on the right device